# Sudo required for doing docker build
sudo: required
services:
- docker

# Build the docker image
script:
- docker build -t ${TRAVIS_COMMIT} .

# If successful, see if we need to publish also
after_success:
- test -z $TRAVIS_TAG && travis_terminate 0
- docker tag ${TRAVIS_COMMIT} killrvideo/killrvideo-dse-config:${TRAVIS_TAG}
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push killrvideo/killrvideo-dse-config:${TRAVIS_TAG}

# Environment variables needed when publishing
env:
  global:
  # DOCKER_USER
  - secure: "KdSSi7s3FConD7IdRln+n/BaC9ttVeXiiHEjANEJ5skL0CNEfDlfJrjFCMlg30Afgu29jqje2CA870dynaRttTbvjGxgplIt75kdh1Ec77Z78n2XlJzOcmXSuK20fEOB58QOi3BLHBOFaGWGMk6eL9Se4MEV8TthOz2mIsLUhBCGJNYVu+CZkaygWvg6kVPB2RJyGIfKiayaWY8oNHkSEOCEV/jEIzt5mT/ljKcekAToao5xmxihdQ6FVVEEAAyAWabvAcUMtdVrZxUQzdt0iRnR8mU7FP/JK0Pt0+AYiS7hVGZSKzdsUqReAKLvI1m2H6jP3WZKOx51QZsdwI33ZB77aqY2A+B0ZEhr6GB3GHlklMiDZ0MB5adgu9c3xLIRocqwc4+5cQbil+y5elLSJ6WW2urkwhlroFg7denmxeknIOoXJBkArv/pPLmelv4CwivAHdSD9gEDMYeF+rizgEjl7SAPnuf8ME5XP2gGwYw2+8Kw8KuJtyJ/VR9dYrRHY5AfvgmHKH3IbGBZwqgu0MiPIXwn56InhYmW8UoBGwCxONtuJdVFQqa4eCFOkaYbJx32aU33ikUCVV+1aKzZzvvUsKxA0ODdgojvf6EMJnMR2OeZkYFqNWwZoFsrYlsNuGXZ9OzZRLU+Vmsxqs6RMgvC6xnXfkhz/PcQyNvroho="
  # DOCKER_PASS
  - secure: "rAQ367dEidPnQxugBU5E1xiDzV3ohOiEfY8nhvmN0+0N8KgYIPbkeOjgENLAtX8Ilwq3tyyxsFHs9xyImr4Btt0amHC0GUiYY4ZX2/NbSUSIx0AoFzWwE53ZjergfvEzPfGti62csaQw0A7M9LVGcNYFjvie2sCWBdAXayDfwwQIA7/eZSvjvDP+Yeo5m9uYNt3zST71JadBZSPj0m2tF60NAQEVIPmQestUdm7p4/Ib31MDKuxkjV84mQUn5aWtuIOPPX83W+Cb/A5pE9A5U1nc6FGjsAvYf11nf8++bcQA9K2hJgFytDb3dj0sidEqIxsvCRdDJE9Hnb4idEfacbPkCwm8yKSoFtRbvRwfv6g7GuoZGCNwjHEmMx+w5/ytFyor0lYzRG8CWJ5SVpJzYNTjkKGz6dwCAtlY3q4xeydvK4FXtSgbSuQ2Tre302QIqH6BkJFFnFgxO6XMJkuCeVJLsGtkiq9uX+FDOrrCBnk800WjfuICagL+IJ+0XEmJAg3+ovcKhR6PfHDHx+T9QhXBONm/eaqQk0bg9nGE3v3ExLZ/UpdClwdrt7XwkMVoIwiRBVkCXhKMbvQKUi4Ql82QLWoDBQdsTyAl5m7X+NZPdacVkShjPrStxK8eX1vzGMp+ln0zP3iT58zE3zDAy/Y2Kfsjao4AJmNgbIqixDY="
